### ISSUE TITLE
.bashrc line 953 get-randint

### ISSUE THREAD

**Issue by W5ALC** [rawiriblundell/dotfiles#2]
Currently the function get-randint at line 953 has a typo so it wont run as is when called in genpasswd. Currently it is defined as 

get-get-randint() {

instead of the intended

get-randint() {

Just thought you might want to know. 

Side note: this is absolutely the best formatted bashrc I've come across. I use so many functions from here and have made a few of my own with tricks i learned from going through this repo. Excellent work and thank you.

**Comment by rawiriblundell** [comment]
Hi!
I had noticed that too some time ago, my guess is that I had an enthusiastic session with `sed` one day back here:

https://github.com/rawiriblundell/dotfiles/commit/4019bdba94136243f127280cfa8e5e98084febbd

I'd already fixed this in my running copy but not committed it back up - which I've done now.

Thanks for the heads up, and thanks for the kind comments :)

Cheers

Rawiri
